# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 559d0e0e156218d1b5f270d77a9d536108cfd83a81ca546a28bf0bf682923490756250515eb6f2da439790a987fd9bb46e3a9b900c42079a4d1c647abea54db0

test:
  secret_key_base: b8513ad4fd231ae09138e022f1193f99480e0bf46e08a82665178a6956681ee8f661f3762a0779703898c8073b43fac786ee3731e785c92cf2a8f3636f912af0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
